// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/kb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Zone classification
type Zone int32

const (
	Zone_SAFE        Zone = 0
	Zone_SUSPICIOUS  Zone = 1
	Zone_BORDERLANDS Zone = 2
)

// Enum value maps for Zone.
var (
	Zone_name = map[int32]string{
		0: "SAFE",
		1: "SUSPICIOUS",
		2: "BORDERLANDS",
	}
	Zone_value = map[string]int32{
		"SAFE":        0,
		"SUSPICIOUS":  1,
		"BORDERLANDS": 2,
	}
)

func (x Zone) Enum() *Zone {
	p := new(Zone)
	*p = x
	return p
}

func (x Zone) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Zone) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kb_proto_enumTypes[0].Descriptor()
}

func (Zone) Type() protoreflect.EnumType {
	return &file_proto_kb_proto_enumTypes[0]
}

func (x Zone) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Zone.Descriptor instead.
func (Zone) EnumDescriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{0}
}

// Containment level
type ContainmentLevel int32

const (
	ContainmentLevel_NONE      ContainmentLevel = 0
	ContainmentLevel_CGROUP    ContainmentLevel = 1
	ContainmentLevel_SECCOMP   ContainmentLevel = 2
	ContainmentLevel_NAMESPACE ContainmentLevel = 3
	ContainmentLevel_TERMINATE ContainmentLevel = 4
)

// Enum value maps for ContainmentLevel.
var (
	ContainmentLevel_name = map[int32]string{
		0: "NONE",
		1: "CGROUP",
		2: "SECCOMP",
		3: "NAMESPACE",
		4: "TERMINATE",
	}
	ContainmentLevel_value = map[string]int32{
		"NONE":      0,
		"CGROUP":    1,
		"SECCOMP":   2,
		"NAMESPACE": 3,
		"TERMINATE": 4,
	}
)

func (x ContainmentLevel) Enum() *ContainmentLevel {
	p := new(ContainmentLevel)
	*p = x
	return p
}

func (x ContainmentLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainmentLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kb_proto_enumTypes[1].Descriptor()
}

func (ContainmentLevel) Type() protoreflect.EnumType {
	return &file_proto_kb_proto_enumTypes[1]
}

func (x ContainmentLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainmentLevel.Descriptor instead.
func (ContainmentLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{1}
}

// Process state
type ProcessState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Zone          Zone                   `protobuf:"varint,5,opt,name=zone,proto3,enum=kb.Zone" json:"zone,omitempty"`
	Uid           uint32                 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Containment   ContainmentLevel       `protobuf:"varint,7,opt,name=containment,proto3,enum=kb.ContainmentLevel" json:"containment,omitempty"`
	FirstSeen     int64                  `protobuf:"varint,8,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      int64                  `protobuf:"varint,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessState) Reset() {
	*x = ProcessState{}
	mi := &file_proto_kb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessState) ProtoMessage() {}

func (x *ProcessState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessState.ProtoReflect.Descriptor instead.
func (*ProcessState) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessState) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessState) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessState) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProcessState) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProcessState) GetZone() Zone {
	if x != nil {
		return x.Zone
	}
	return Zone_SAFE
}

func (x *ProcessState) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessState) GetContainment() ContainmentLevel {
	if x != nil {
		return x.Containment
	}
	return ContainmentLevel_NONE
}

func (x *ProcessState) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *ProcessState) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// KB Event from eBPF layer
type KBEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ScoreDelta    float32                `protobuf:"fixed32,5,opt,name=score_delta,json=scoreDelta,proto3" json:"score_delta,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KBEvent) Reset() {
	*x = KBEvent{}
	mi := &file_proto_kb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KBEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBEvent) ProtoMessage() {}

func (x *KBEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBEvent.ProtoReflect.Descriptor instead.
func (*KBEvent) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{1}
}

func (x *KBEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *KBEvent) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *KBEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *KBEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *KBEvent) GetScoreDelta() float32 {
	if x != nil {
		return x.ScoreDelta
	}
	return 0
}

func (x *KBEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KBEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Alert
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	AlertType     string                 `protobuf:"bytes,2,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	Pid           uint32                 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,4,opt,name=comm,proto3" json:"comm,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Evidence      []string               `protobuf:"bytes,8,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_kb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *Alert) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Alert) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Alert) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Alert) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// Agent decision
type AgentDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AuthorizedBy  []string               `protobuf:"bytes,6,rep,name=authorized_by,json=authorizedBy,proto3" json:"authorized_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDecision) Reset() {
	*x = AgentDecision{}
	mi := &file_proto_kb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDecision) ProtoMessage() {}

func (x *AgentDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDecision.ProtoReflect.Descriptor instead.
func (*AgentDecision) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{3}
}

func (x *AgentDecision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *AgentDecision) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentDecision) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AgentDecision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentDecision) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AgentDecision) GetAuthorizedBy() []string {
	if x != nil {
		return x.AuthorizedBy
	}
	return nil
}

// Requests/Responses
type PidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PidRequest) Reset() {
	*x = PidRequest{}
	mi := &file_proto_kb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidRequest) ProtoMessage() {}

func (x *PidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidRequest.ProtoReflect.Descriptor instead.
func (*PidRequest) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{4}
}

func (x *PidRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          Zone                   `protobuf:"varint,1,opt,name=zone,proto3,enum=kb.Zone" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneRequest) Reset() {
	*x = ZoneRequest{}
	mi := &file_proto_kb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneRequest) ProtoMessage() {}

func (x *ZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneRequest.ProtoReflect.Descriptor instead.
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneRequest) GetZone() Zone {
	if x != nil {
		return x.Zone
	}
	return Zone_SAFE
}

type EventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_proto_kb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{6}
}

func (x *EventFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type DecisionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionAck) Reset() {
	*x = DecisionAck{}
	mi := &file_proto_kb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionAck) ProtoMessage() {}

func (x *DecisionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionAck.ProtoReflect.Descriptor instead.
func (*DecisionAck) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{7}
}

func (x *DecisionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecisionAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContainmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Level         ContainmentLevel       `protobuf:"varint,2,opt,name=level,proto3,enum=kb.ContainmentLevel" json:"level,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainmentRequest) Reset() {
	*x = ContainmentRequest{}
	mi := &file_proto_kb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainmentRequest) ProtoMessage() {}

func (x *ContainmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainmentRequest.ProtoReflect.Descriptor instead.
func (*ContainmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{8}
}

func (x *ContainmentRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ContainmentRequest) GetLevel() ContainmentLevel {
	if x != nil {
		return x.Level
	}
	return ContainmentLevel_NONE
}

func (x *ContainmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ContainmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainmentResponse) Reset() {
	*x = ContainmentResponse{}
	mi := &file_proto_kb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainmentResponse) ProtoMessage() {}

func (x *ContainmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainmentResponse.ProtoReflect.Descriptor instead.
func (*ContainmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{9}
}

func (x *ContainmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_kb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{10}
}

type SystemStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventsPerSecond float64                `protobuf:"fixed64,1,opt,name=events_per_second,json=eventsPerSecond,proto3" json:"events_per_second,omitempty"`
	ActiveProcesses uint32                 `protobuf:"varint,2,opt,name=active_processes,json=activeProcesses,proto3" json:"active_processes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_proto_kb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{11}
}

func (x *SystemStats) GetEventsPerSecond() float64 {
	if x != nil {
		return x.EventsPerSecond
	}
	return 0
}

func (x *SystemStats) GetActiveProcesses() uint32 {
	if x != nil {
		return x.ActiveProcesses
	}
	return 0
}

// A single hash-chained audit_log row (internal/audit/audit.go).
type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsNs          int64                  `protobuf:"varint,1,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	PrevHash      string                 `protobuf:"bytes,6,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	EntryHash     string                 `protobuf:"bytes,7,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_proto_kb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{12}
}

func (x *AuditEntry) GetTsNs() int64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEntry) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *AuditEntry) GetEntryHash() string {
	if x != nil {
		return x.EntryHash
	}
	return ""
}

type AuditVerifyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainIntact     bool                   `protobuf:"varint,1,opt,name=chain_intact,json=chainIntact,proto3" json:"chain_intact,omitempty"`
	EntriesVerified uint32                 `protobuf:"varint,2,opt,name=entries_verified,json=entriesVerified,proto3" json:"entries_verified,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditVerifyResponse) Reset() {
	*x = AuditVerifyResponse{}
	mi := &file_proto_kb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditVerifyResponse) ProtoMessage() {}

func (x *AuditVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditVerifyResponse.ProtoReflect.Descriptor instead.
func (*AuditVerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{13}
}

func (x *AuditVerifyResponse) GetChainIntact() bool {
	if x != nil {
		return x.ChainIntact
	}
	return false
}

func (x *AuditVerifyResponse) GetEntriesVerified() uint32 {
	if x != nil {
		return x.EntriesVerified
	}
	return 0
}

func (x *AuditVerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuditExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditExportResponse) Reset() {
	*x = AuditExportResponse{}
	mi := &file_proto_kb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditExportResponse) ProtoMessage() {}

func (x *AuditExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditExportResponse.ProtoReflect.Descriptor instead.
func (*AuditExportResponse) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{14}
}

func (x *AuditExportResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ZoneOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Zone          Zone                   `protobuf:"varint,2,opt,name=zone,proto3,enum=kb.Zone" json:"zone,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneOverrideRequest) Reset() {
	*x = ZoneOverrideRequest{}
	mi := &file_proto_kb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneOverrideRequest) ProtoMessage() {}

func (x *ZoneOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneOverrideRequest.ProtoReflect.Descriptor instead.
func (*ZoneOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{15}
}

func (x *ZoneOverrideRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ZoneOverrideRequest) GetZone() Zone {
	if x != nil {
		return x.Zone
	}
	return Zone_SAFE
}

func (x *ZoneOverrideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ZoneOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneOverrideResponse) Reset() {
	*x = ZoneOverrideResponse{}
	mi := &file_proto_kb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneOverrideResponse) ProtoMessage() {}

func (x *ZoneOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneOverrideResponse.ProtoReflect.Descriptor instead.
func (*ZoneOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{16}
}

func (x *ZoneOverrideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReloadPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPolicyResponse) Reset() {
	*x = ReloadPolicyResponse{}
	mi := &file_proto_kb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPolicyResponse) ProtoMessage() {}

func (x *ReloadPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPolicyResponse.ProtoReflect.Descriptor instead.
func (*ReloadPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_kb_proto_rawDescGZIP(), []int{17}
}

func (x *ReloadPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadPolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_kb_proto protoreflect.FileDescriptor

const file_proto_kb_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kb.proto\x12\x02kb\"\x82\x02\n" +
	"\fProcessState\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x1c\n" +
	"\x04zone\x18\x05 \x01(\x0e2\b.kb.ZoneR\x04zone\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\x126\n" +
	"\vcontainment\x18\a \x01(\x0e2\x14.kb.ContainmentLevelR\vcontainment\x12\x1d\n" +
	"\n" +
	"first_seen\x18\b \x01(\x03R\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\t \x01(\x03R\blastSeen\"\x95\x02\n" +
	"\aKBEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1f\n" +
	"\vscore_delta\x18\x05 \x01(\x02R\n" +
	"scoreDelta\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x125\n" +
	"\bmetadata\x18\a \x03(\v2\x19.kb.KBEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x02 \x01(\tR\talertType\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x04 \x01(\tR\x04comm\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bevidence\x18\b \x03(\tR\bevidence\"\xba\x01\n" +
	"\rAgentDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\rR\x03pid\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rauthorized_by\x18\x06 \x03(\tR\fauthorizedBy\"\x1e\n" +
	"\n" +
	"PidRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"+\n" +
	"\vZoneRequest\x12\x1c\n" +
	"\x04zone\x18\x01 \x01(\x0e2\b.kb.ZoneR\x04zone\".\n" +
	"\vEventFilter\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"A\n" +
	"\vDecisionAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x12ContainmentRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12*\n" +
	"\x05level\x18\x02 \x01(\x0e2\x14.kb.ContainmentLevelR\x05level\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"/\n" +
	"\x13ContainmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty\"d\n" +
	"\vSystemStats\x12*\n" +
	"\x11events_per_second\x18\x01 \x01(\x01R\x0feventsPerSecond\x12)\n" +
	"\x10active_processes\x18\x02 \x01(\rR\x0factiveProcesses\"\xbd\x01\n" +
	"\n" +
	"AuditEntry\x12\x13\n" +
	"\x05ts_ns\x18\x01 \x01(\x03R\x04tsNs\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1b\n" +
	"\tprev_hash\x18\x06 \x01(\tR\bprevHash\x12\x1d\n" +
	"\n" +
	"entry_hash\x18\a \x01(\tR\tentryHash\"y\n" +
	"\x13AuditVerifyResponse\x12!\n" +
	"\fchain_intact\x18\x01 \x01(\bR\vchainIntact\x12)\n" +
	"\x10entries_verified\x18\x02 \x01(\rR\x0fentriesVerified\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"?\n" +
	"\x13AuditExportResponse\x12(\n" +
	"\aentries\x18\x01 \x03(\v2\x0e.kb.AuditEntryR\aentries\"]\n" +
	"\x13ZoneOverrideRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x1c\n" +
	"\x04zone\x18\x02 \x01(\x0e2\b.kb.ZoneR\x04zone\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"0\n" +
	"\x14ZoneOverrideResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x14ReloadPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*1\n" +
	"\x04Zone\x12\b\n" +
	"\x04SAFE\x10\x00\x12\x0e\n" +
	"\n" +
	"SUSPICIOUS\x10\x01\x12\x0f\n" +
	"\vBORDERLANDS\x10\x02*S\n" +
	"\x10ContainmentLevel\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06CGROUP\x10\x01\x12\v\n" +
	"\aSECCOMP\x10\x02\x12\r\n" +
	"\tNAMESPACE\x10\x03\x12\r\n" +
	"\tTERMINATE\x10\x042\xe9\x04\n" +
	"\x11KernelBorderlands\x123\n" +
	"\x0fGetProcessState\x12\x0e.kb.PidRequest\x1a\x10.kb.ProcessState\x12/\n" +
	"\bListZone\x12\x0f.kb.ZoneRequest\x1a\x10.kb.ProcessState0\x01\x12A\n" +
	"\x0eSetContainment\x12\x16.kb.ContainmentRequest\x1a\x17.kb.ContainmentResponse\x12.\n" +
	"\fStreamEvents\x12\x0f.kb.EventFilter\x1a\v.kb.KBEvent0\x01\x129\n" +
	"\x13SubmitAgentDecision\x12\x11.kb.AgentDecision\x1a\x0f.kb.DecisionAck\x12,\n" +
	"\fStreamAlerts\x12\x0f.kb.EventFilter\x1a\t.kb.Alert0\x01\x12,\n" +
	"\x0eGetSystemStats\x12\t.kb.Empty\x1a\x0f.kb.SystemStats\x126\n" +
	"\x10VerifyAuditChain\x12\t.kb.Empty\x1a\x17.kb.AuditVerifyResponse\x124\n" +
	"\x0eExportAuditLog\x12\t.kb.Empty\x1a\x17.kb.AuditExportResponse\x12A\n" +
	"\fOverrideZone\x12\x17.kb.ZoneOverrideRequest\x1a\x18.kb.ZoneOverrideResponse\x123\n" +
	"\fReloadPolicy\x12\t.kb.Empty\x1a\x18.kb.ReloadPolicyResponseBCZAgithub.com/pardhuvarmax/kernel-borderlands/kb-control-plane/protob\x06proto3"

var (
	file_proto_kb_proto_rawDescOnce sync.Once
	file_proto_kb_proto_rawDescData []byte
)

func file_proto_kb_proto_rawDescGZIP() []byte {
	file_proto_kb_proto_rawDescOnce.Do(func() {
		file_proto_kb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kb_proto_rawDesc), len(file_proto_kb_proto_rawDesc)))
	})
	return file_proto_kb_proto_rawDescData
}

var file_proto_kb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_kb_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_kb_proto_goTypes = []any{
	(Zone)(0),                    // 0: kb.Zone
	(ContainmentLevel)(0),        // 1: kb.ContainmentLevel
	(*ProcessState)(nil),         // 2: kb.ProcessState
	(*KBEvent)(nil),              // 3: kb.KBEvent
	(*Alert)(nil),                // 4: kb.Alert
	(*AgentDecision)(nil),        // 5: kb.AgentDecision
	(*PidRequest)(nil),           // 6: kb.PidRequest
	(*ZoneRequest)(nil),          // 7: kb.ZoneRequest
	(*EventFilter)(nil),          // 8: kb.EventFilter
	(*DecisionAck)(nil),          // 9: kb.DecisionAck
	(*ContainmentRequest)(nil),   // 10: kb.ContainmentRequest
	(*ContainmentResponse)(nil),  // 11: kb.ContainmentResponse
	(*Empty)(nil),                // 12: kb.Empty
	(*SystemStats)(nil),          // 13: kb.SystemStats
	(*AuditEntry)(nil),           // 14: kb.AuditEntry
	(*AuditVerifyResponse)(nil),  // 15: kb.AuditVerifyResponse
	(*AuditExportResponse)(nil),  // 16: kb.AuditExportResponse
	(*ZoneOverrideRequest)(nil),  // 17: kb.ZoneOverrideRequest
	(*ZoneOverrideResponse)(nil), // 18: kb.ZoneOverrideResponse
	(*ReloadPolicyResponse)(nil), // 19: kb.ReloadPolicyResponse
	nil,                          // 20: kb.KBEvent.MetadataEntry
}
var file_proto_kb_proto_depIdxs = []int32{
	0,  // 0: kb.ProcessState.zone:type_name -> kb.Zone
	1,  // 1: kb.ProcessState.containment:type_name -> kb.ContainmentLevel
	20, // 2: kb.KBEvent.metadata:type_name -> kb.KBEvent.MetadataEntry
	0,  // 3: kb.ZoneRequest.zone:type_name -> kb.Zone
	1,  // 4: kb.ContainmentRequest.level:type_name -> kb.ContainmentLevel
	14, // 5: kb.AuditExportResponse.entries:type_name -> kb.AuditEntry
	0,  // 6: kb.ZoneOverrideRequest.zone:type_name -> kb.Zone
	6,  // 7: kb.KernelBorderlands.GetProcessState:input_type -> kb.PidRequest
	7,  // 8: kb.KernelBorderlands.ListZone:input_type -> kb.ZoneRequest
	10, // 9: kb.KernelBorderlands.SetContainment:input_type -> kb.ContainmentRequest
	8,  // 10: kb.KernelBorderlands.StreamEvents:input_type -> kb.EventFilter
	5,  // 11: kb.KernelBorderlands.SubmitAgentDecision:input_type -> kb.AgentDecision
	8,  // 12: kb.KernelBorderlands.StreamAlerts:input_type -> kb.EventFilter
	12, // 13: kb.KernelBorderlands.GetSystemStats:input_type -> kb.Empty
	12, // 14: kb.KernelBorderlands.VerifyAuditChain:input_type -> kb.Empty
	12, // 15: kb.KernelBorderlands.ExportAuditLog:input_type -> kb.Empty
	17, // 16: kb.KernelBorderlands.OverrideZone:input_type -> kb.ZoneOverrideRequest
	12, // 17: kb.KernelBorderlands.ReloadPolicy:input_type -> kb.Empty
	2,  // 18: kb.KernelBorderlands.GetProcessState:output_type -> kb.ProcessState
	2,  // 19: kb.KernelBorderlands.ListZone:output_type -> kb.ProcessState
	11, // 20: kb.KernelBorderlands.SetContainment:output_type -> kb.ContainmentResponse
	3,  // 21: kb.KernelBorderlands.StreamEvents:output_type -> kb.KBEvent
	9,  // 22: kb.KernelBorderlands.SubmitAgentDecision:output_type -> kb.DecisionAck
	4,  // 23: kb.KernelBorderlands.StreamAlerts:output_type -> kb.Alert
	13, // 24: kb.KernelBorderlands.GetSystemStats:output_type -> kb.SystemStats
	15, // 25: kb.KernelBorderlands.VerifyAuditChain:output_type -> kb.AuditVerifyResponse
	16, // 26: kb.KernelBorderlands.ExportAuditLog:output_type -> kb.AuditExportResponse
	18, // 27: kb.KernelBorderlands.OverrideZone:output_type -> kb.ZoneOverrideResponse
	19, // 28: kb.KernelBorderlands.ReloadPolicy:output_type -> kb.ReloadPolicyResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_kb_proto_init() }
func file_proto_kb_proto_init() {
	if File_proto_kb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kb_proto_rawDesc), len(file_proto_kb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kb_proto_goTypes,
		DependencyIndexes: file_proto_kb_proto_depIdxs,
		EnumInfos:         file_proto_kb_proto_enumTypes,
		MessageInfos:      file_proto_kb_proto_msgTypes,
	}.Build()
	File_proto_kb_proto = out.File
	file_proto_kb_proto_goTypes = nil
	file_proto_kb_proto_depIdxs = nil
}
