// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/kb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelBorderlands_GetProcessState_FullMethodName     = "/kb.KernelBorderlands/GetProcessState"
	KernelBorderlands_ListZone_FullMethodName            = "/kb.KernelBorderlands/ListZone"
	KernelBorderlands_SetContainment_FullMethodName      = "/kb.KernelBorderlands/SetContainment"
	KernelBorderlands_StreamEvents_FullMethodName        = "/kb.KernelBorderlands/StreamEvents"
	KernelBorderlands_SubmitAgentDecision_FullMethodName = "/kb.KernelBorderlands/SubmitAgentDecision"
	KernelBorderlands_StreamAlerts_FullMethodName        = "/kb.KernelBorderlands/StreamAlerts"
)

// KernelBorderlandsClient is the client API for KernelBorderlands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KB Control Plane Service
type KernelBorderlandsClient interface {
	// Query process state
	GetProcessState(ctx context.Context, in *PidRequest, opts ...grpc.CallOption) (*ProcessState, error)
	// List processes in a zone
	ListZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessState], error)
	// Set containment level
	SetContainment(ctx context.Context, in *ContainmentRequest, opts ...grpc.CallOption) (*ContainmentResponse, error)
	// Stream real-time events
	StreamEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KBEvent], error)
	// Submit agent decision
	SubmitAgentDecision(ctx context.Context, in *AgentDecision, opts ...grpc.CallOption) (*DecisionAck, error)
	// Stream alerts
	StreamAlerts(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Alert], error)
}

type kernelBorderlandsClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelBorderlandsClient(cc grpc.ClientConnInterface) KernelBorderlandsClient {
	return &kernelBorderlandsClient{cc}
}

func (c *kernelBorderlandsClient) GetProcessState(ctx context.Context, in *PidRequest, opts ...grpc.CallOption) (*ProcessState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessState)
	err := c.cc.Invoke(ctx, KernelBorderlands_GetProcessState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelBorderlandsClient) ListZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelBorderlands_ServiceDesc.Streams[0], KernelBorderlands_ListZone_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ZoneRequest, ProcessState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBorderlands_ListZoneClient = grpc.ServerStreamingClient[ProcessState]

func (c *kernelBorderlandsClient) SetContainment(ctx context.Context, in *ContainmentRequest, opts ...grpc.CallOption) (*ContainmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainmentResponse)
	err := c.cc.Invoke(ctx, KernelBorderlands_SetContainment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelBorderlandsClient) StreamEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KBEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelBorderlands_ServiceDesc.Streams[1], KernelBorderlands_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventFilter, KBEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBorderlands_StreamEventsClient = grpc.ServerStreamingClient[KBEvent]

func (c *kernelBorderlandsClient) SubmitAgentDecision(ctx context.Context, in *AgentDecision, opts ...grpc.CallOption) (*DecisionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionAck)
	err := c.cc.Invoke(ctx, KernelBorderlands_SubmitAgentDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelBorderlandsClient) StreamAlerts(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Alert], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelBorderlands_ServiceDesc.Streams[2], KernelBorderlands_StreamAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventFilter, Alert]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBorderlands_StreamAlertsClient = grpc.ServerStreamingClient[Alert]

// KernelBorderlandsServer is the server API for KernelBorderlands service.
// All implementations must embed UnimplementedKernelBorderlandsServer
// for forward compatibility.
//
// KB Control Plane Service
type KernelBorderlandsServer interface {
	// Query process state
	GetProcessState(context.Context, *PidRequest) (*ProcessState, error)
	// List processes in a zone
	ListZone(*ZoneRequest, grpc.ServerStreamingServer[ProcessState]) error
	// Set containment level
	SetContainment(context.Context, *ContainmentRequest) (*ContainmentResponse, error)
	// Stream real-time events
	StreamEvents(*EventFilter, grpc.ServerStreamingServer[KBEvent]) error
	// Submit agent decision
	SubmitAgentDecision(context.Context, *AgentDecision) (*DecisionAck, error)
	// Stream alerts
	StreamAlerts(*EventFilter, grpc.ServerStreamingServer[Alert]) error
	mustEmbedUnimplementedKernelBorderlandsServer()
}

// UnimplementedKernelBorderlandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelBorderlandsServer struct{}

func (UnimplementedKernelBorderlandsServer) GetProcessState(context.Context, *PidRequest) (*ProcessState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcessState not implemented")
}
func (UnimplementedKernelBorderlandsServer) ListZone(*ZoneRequest, grpc.ServerStreamingServer[ProcessState]) error {
	return status.Error(codes.Unimplemented, "method ListZone not implemented")
}
func (UnimplementedKernelBorderlandsServer) SetContainment(context.Context, *ContainmentRequest) (*ContainmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetContainment not implemented")
}
func (UnimplementedKernelBorderlandsServer) StreamEvents(*EventFilter, grpc.ServerStreamingServer[KBEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedKernelBorderlandsServer) SubmitAgentDecision(context.Context, *AgentDecision) (*DecisionAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAgentDecision not implemented")
}
func (UnimplementedKernelBorderlandsServer) StreamAlerts(*EventFilter, grpc.ServerStreamingServer[Alert]) error {
	return status.Error(codes.Unimplemented, "method StreamAlerts not implemented")
}
func (UnimplementedKernelBorderlandsServer) mustEmbedUnimplementedKernelBorderlandsServer() {}
func (UnimplementedKernelBorderlandsServer) testEmbeddedByValue()                           {}

// UnsafeKernelBorderlandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelBorderlandsServer will
// result in compilation errors.
type UnsafeKernelBorderlandsServer interface {
	mustEmbedUnimplementedKernelBorderlandsServer()
}

func RegisterKernelBorderlandsServer(s grpc.ServiceRegistrar, srv KernelBorderlandsServer) {
	// If the following call panics, it indicates UnimplementedKernelBorderlandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelBorderlands_ServiceDesc, srv)
}

func _KernelBorderlands_GetProcessState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBorderlandsServer).GetProcessState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBorderlands_GetProcessState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBorderlandsServer).GetProcessState(ctx, req.(*PidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelBorderlands_ListZone_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ZoneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelBorderlandsServer).ListZone(m, &grpc.GenericServerStream[ZoneRequest, ProcessState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBorderlands_ListZoneServer = grpc.ServerStreamingServer[ProcessState]

func _KernelBorderlands_SetContainment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBorderlandsServer).SetContainment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBorderlands_SetContainment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBorderlandsServer).SetContainment(ctx, req.(*ContainmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelBorderlands_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelBorderlandsServer).StreamEvents(m, &grpc.GenericServerStream[EventFilter, KBEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBorderlands_StreamEventsServer = grpc.ServerStreamingServer[KBEvent]

func _KernelBorderlands_SubmitAgentDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentDecision)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBorderlandsServer).SubmitAgentDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBorderlands_SubmitAgentDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBorderlandsServer).SubmitAgentDecision(ctx, req.(*AgentDecision))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelBorderlands_StreamAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelBorderlandsServer).StreamAlerts(m, &grpc.GenericServerStream[EventFilter, Alert]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBorderlands_StreamAlertsServer = grpc.ServerStreamingServer[Alert]

// KernelBorderlands_ServiceDesc is the grpc.ServiceDesc for KernelBorderlands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelBorderlands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kb.KernelBorderlands",
	HandlerType: (*KernelBorderlandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProcessState",
			Handler:    _KernelBorderlands_GetProcessState_Handler,
		},
		{
			MethodName: "SetContainment",
			Handler:    _KernelBorderlands_SetContainment_Handler,
		},
		{
			MethodName: "SubmitAgentDecision",
			Handler:    _KernelBorderlands_SubmitAgentDecision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListZone",
			Handler:       _KernelBorderlands_ListZone_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _KernelBorderlands_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAlerts",
			Handler:       _KernelBorderlands_StreamAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kb.proto",
}
