# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kb_pb2 as kb__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelBorderlandsStub:
    """KB Control Plane Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProcessState = channel.unary_unary(
                '/kb.KernelBorderlands/GetProcessState',
                request_serializer=kb__pb2.PidRequest.SerializeToString,
                response_deserializer=kb__pb2.ProcessState.FromString,
                _registered_method=True)
        self.ListZone = channel.unary_stream(
                '/kb.KernelBorderlands/ListZone',
                request_serializer=kb__pb2.ZoneRequest.SerializeToString,
                response_deserializer=kb__pb2.ProcessState.FromString,
                _registered_method=True)
        self.SetContainment = channel.unary_unary(
                '/kb.KernelBorderlands/SetContainment',
                request_serializer=kb__pb2.ContainmentRequest.SerializeToString,
                response_deserializer=kb__pb2.ContainmentResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/kb.KernelBorderlands/StreamEvents',
                request_serializer=kb__pb2.EventFilter.SerializeToString,
                response_deserializer=kb__pb2.KBEvent.FromString,
                _registered_method=True)
        self.SubmitAgentDecision = channel.unary_unary(
                '/kb.KernelBorderlands/SubmitAgentDecision',
                request_serializer=kb__pb2.AgentDecision.SerializeToString,
                response_deserializer=kb__pb2.DecisionAck.FromString,
                _registered_method=True)
        self.StreamAlerts = channel.unary_stream(
                '/kb.KernelBorderlands/StreamAlerts',
                request_serializer=kb__pb2.EventFilter.SerializeToString,
                response_deserializer=kb__pb2.Alert.FromString,
                _registered_method=True)


class KernelBorderlandsServicer:
    """KB Control Plane Service
    """

    def GetProcessState(self, request, context):
        """Query process state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListZone(self, request, context):
        """List processes in a zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetContainment(self, request, context):
        """Set containment level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Stream real-time events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAgentDecision(self, request, context):
        """Submit agent decision
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlerts(self, request, context):
        """Stream alerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelBorderlandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProcessState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessState,
                    request_deserializer=kb__pb2.PidRequest.FromString,
                    response_serializer=kb__pb2.ProcessState.SerializeToString,
            ),
            'ListZone': grpc.unary_stream_rpc_method_handler(
                    servicer.ListZone,
                    request_deserializer=kb__pb2.ZoneRequest.FromString,
                    response_serializer=kb__pb2.ProcessState.SerializeToString,
            ),
            'SetContainment': grpc.unary_unary_rpc_method_handler(
                    servicer.SetContainment,
                    request_deserializer=kb__pb2.ContainmentRequest.FromString,
                    response_serializer=kb__pb2.ContainmentResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=kb__pb2.EventFilter.FromString,
                    response_serializer=kb__pb2.KBEvent.SerializeToString,
            ),
            'SubmitAgentDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAgentDecision,
                    request_deserializer=kb__pb2.AgentDecision.FromString,
                    response_serializer=kb__pb2.DecisionAck.SerializeToString,
            ),
            'StreamAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlerts,
                    request_deserializer=kb__pb2.EventFilter.FromString,
                    response_serializer=kb__pb2.Alert.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kb.KernelBorderlands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kb.KernelBorderlands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KernelBorderlands:
    """KB Control Plane Service
    """

    @staticmethod
    def GetProcessState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.KernelBorderlands/GetProcessState',
            kb__pb2.PidRequest.SerializeToString,
            kb__pb2.ProcessState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListZone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kb.KernelBorderlands/ListZone',
            kb__pb2.ZoneRequest.SerializeToString,
            kb__pb2.ProcessState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetContainment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.KernelBorderlands/SetContainment',
            kb__pb2.ContainmentRequest.SerializeToString,
            kb__pb2.ContainmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kb.KernelBorderlands/StreamEvents',
            kb__pb2.EventFilter.SerializeToString,
            kb__pb2.KBEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAgentDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.KernelBorderlands/SubmitAgentDecision',
            kb__pb2.AgentDecision.SerializeToString,
            kb__pb2.DecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kb.KernelBorderlands/StreamAlerts',
            kb__pb2.EventFilter.SerializeToString,
            kb__pb2.Alert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
