// Local copy of kb-checker/proto/checker.proto, with go_package added so
// kb-control-plane can generate a Go client stub. kb-checker (Rust) is the
// canonical owner of this contract — if it changes there, this copy needs
// to be updated to match (same pattern as kb.proto's separately-owned
// C/Go wire structs, just one level up at the proto layer).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: checker.proto

package checker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckerStatus_GetStatus_FullMethodName = "/checker.CheckerStatus/GetStatus"
)

// CheckerStatusClient is the client API for CheckerStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckerStatusClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type checkerStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckerStatusClient(cc grpc.ClientConnInterface) CheckerStatusClient {
	return &checkerStatusClient{cc}
}

func (c *checkerStatusClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CheckerStatus_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckerStatusServer is the server API for CheckerStatus service.
// All implementations must embed UnimplementedCheckerStatusServer
// for forward compatibility.
type CheckerStatusServer interface {
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedCheckerStatusServer()
}

// UnimplementedCheckerStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckerStatusServer struct{}

func (UnimplementedCheckerStatusServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCheckerStatusServer) mustEmbedUnimplementedCheckerStatusServer() {}
func (UnimplementedCheckerStatusServer) testEmbeddedByValue()                       {}

// UnsafeCheckerStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckerStatusServer will
// result in compilation errors.
type UnsafeCheckerStatusServer interface {
	mustEmbedUnimplementedCheckerStatusServer()
}

func RegisterCheckerStatusServer(s grpc.ServiceRegistrar, srv CheckerStatusServer) {
	// If the following call panics, it indicates UnimplementedCheckerStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckerStatus_ServiceDesc, srv)
}

func _CheckerStatus_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerStatusServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckerStatus_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerStatusServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckerStatus_ServiceDesc is the grpc.ServiceDesc for CheckerStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckerStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checker.CheckerStatus",
	HandlerType: (*CheckerStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _CheckerStatus_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checker.proto",
}
